sudo: required
services:
  - docker

before_install:
  - docker build -t grovejam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run grovejam/react-test npm test -- --coverage
# after_success:
#   - docker build -t grovejam/multi-client ./client
#   - docker build -t grovejam/multi-nginx ./nginx
#   - docker build -t grovejam/multi-server ./server
#   - docker build -t grovejam/multi-worker ./worker

# script:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker push grovejam/multi-client
#   - docker push grovejam/multi-nginx
#   - docker push grovejam/multi-server
#   - docker push grovejam/multi-worker
